services:
  ubuntu-debug-gcc:
    build:
      context: .
      args:
        CMAKE_BUILD_TYPE: Debug
        CC: gcc
        CXX: g++
    image: todo:ubuntu-debug-gcc

  ubuntu-release-gcc:
    build:
      context: .
      args:
        CMAKE_BUILD_TYPE: Release
        CC: gcc
        CXX: g++
    image: todo:ubuntu-release-gcc

  ubuntu-debug-clang:
    build:
      context: .
      args:
        CMAKE_BUILD_TYPE: Debug
        CC: clang
        CXX: clang++
    image: todo:ubuntu-debug-clang

  ubuntu-release-clang:
    build:
      context: .
      args:
        CMAKE_BUILD_TYPE: Release
        CC: clang
        CXX: clang++
    image: todo:ubuntu-release-clang